package telemetry

import "time"

// AlertType identifies the category of a health alert.
type AlertType string

const (
	AlertErrorRate    AlertType = "error_rate"
	AlertLatency      AlertType = "latency"
	AlertProviderDown AlertType = "provider_down"
)

// AlertConfig defines configurable thresholds and behavior for health alerting.
type AlertConfig struct {
	// ErrorRateThreshold triggers an alert when the platform-wide error rate
	// exceeds this value over ErrorRateWindow. Default: 0.30 (30%).
	ErrorRateThreshold float64 `json:"error_rate_threshold"`

	// ErrorRateWindow is the rolling time window for error rate computation.
	// Default: 10 minutes.
	ErrorRateWindow time.Duration `json:"error_rate_window"`

	// LatencyThreshold triggers an alert when average agent call latency
	// exceeds this duration over LatencyWindow. Default: 60 seconds.
	LatencyThreshold time.Duration `json:"latency_threshold"`

	// LatencyWindow is the rolling time window for latency computation.
	// Default: 5 minutes.
	LatencyWindow time.Duration `json:"latency_window"`

	// ProviderDownAttempts is the number of consecutive failures before
	// a provider is considered unreachable. Default: 3.
	ProviderDownAttempts int `json:"provider_down_attempts"`

	// QuietHoursStart is the UTC hour (0–23) at which quiet hours begin.
	// During quiet hours, non-critical alerts are suppressed.
	QuietHoursStart int `json:"quiet_hours_start"`

	// QuietHoursEnd is the UTC hour (0–23) at which quiet hours end.
	QuietHoursEnd int `json:"quiet_hours_end"`

	// MutedAlertTypes lists alert types that should not be delivered.
	MutedAlertTypes []string `json:"muted_alert_types"`
}

// DefaultAlertConfig returns an AlertConfig with sensible defaults.
func DefaultAlertConfig() AlertConfig {
	return AlertConfig{
		ErrorRateThreshold:   0.30,
		ErrorRateWindow:      10 * time.Minute,
		LatencyThreshold:     60 * time.Second,
		LatencyWindow:        5 * time.Minute,
		ProviderDownAttempts: 3,
		QuietHoursStart:      0,
		QuietHoursEnd:        0,
		MutedAlertTypes:      nil,
	}
}

// Alert represents a health alert generated by the alerting subsystem.
type Alert struct {
	ID        string                 `json:"id"`
	Type      AlertType              `json:"type"`
	Message   string                 `json:"message"`
	Severity  string                 `json:"severity"` // "warning", "critical"
	Timestamp time.Time              `json:"timestamp"`
	Details   map[string]interface{} `json:"details,omitempty"`
}

// Alerter defines the interface for health alert evaluation.
type Alerter interface {
	// Evaluate checks current telemetry state against alert thresholds
	// and returns any triggered alerts.
	Evaluate(config AlertConfig, events []TelemetryEvent) []Alert

	// IsQuietHours returns true if the current time falls within the
	// configured quiet hours window.
	IsQuietHours(config AlertConfig, now time.Time) bool
}
